/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor.ui.contentassist

import fr.inria.diverse.k3.example.logo.xtext_editor.ui.contentassist.AbstractLogoTextualSyntaxProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LogoTextualSyntaxProposalProvider extends AbstractLogoTextualSyntaxProposalProvider {
}
