/*
 * generated by Xtext 2.14.0
 */
package fr.inria.sed.logo.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.sed.logo.xtext.ide.contentassist.antlr.internal.InternalLogoParser;
import fr.inria.sed.logo.xtext.services.LogoGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LogoParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LogoGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LogoGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getBlockInstructionAccess().getAlternatives(), "rule__BlockInstruction__Alternatives");
			builder.put(grammarAccess.getIfAccess().getAlternatives(), "rule__If__Alternatives");
			builder.put(grammarAccess.getComparisonExpressionAccess().getAlternatives_1_0(), "rule__ComparisonExpression__Alternatives_1_0");
			builder.put(grammarAccess.getAddExpressionAccess().getAlternatives_1_0(), "rule__AddExpression__Alternatives_1_0");
			builder.put(grammarAccess.getMultExpressionAccess().getAlternatives_1_0(), "rule__MultExpression__Alternatives_1_0");
			builder.put(grammarAccess.getLiteralsExpressionAccess().getAlternatives(), "rule__LiteralsExpression__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getLogoProgramAccess().getGroup(), "rule__LogoProgram__Group__0");
			builder.put(grammarAccess.getBackwardAccess().getGroup(), "rule__Backward__Group__0");
			builder.put(grammarAccess.getForwardAccess().getGroup(), "rule__Forward__Group__0");
			builder.put(grammarAccess.getLeftAccess().getGroup(), "rule__Left__Group__0");
			builder.put(grammarAccess.getRightAccess().getGroup(), "rule__Right__Group__0");
			builder.put(grammarAccess.getPenDownAccess().getGroup(), "rule__PenDown__Group__0");
			builder.put(grammarAccess.getPenUpAccess().getGroup(), "rule__PenUp__Group__0");
			builder.put(grammarAccess.getClearAccess().getGroup(), "rule__Clear__Group__0");
			builder.put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
			builder.put(grammarAccess.getProcCallAccess().getGroup(), "rule__ProcCall__Group__0");
			builder.put(grammarAccess.getProcCallAccess().getGroup_3(), "rule__ProcCall__Group_3__0");
			builder.put(grammarAccess.getProcDeclarationAccess().getGroup(), "rule__ProcDeclaration__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
			builder.put(grammarAccess.getIfAccess().getGroup_0(), "rule__If__Group_0__0");
			builder.put(grammarAccess.getIfAccess().getGroup_1(), "rule__If__Group_1__0");
			builder.put(grammarAccess.getRepeatAccess().getGroup(), "rule__Repeat__Group__0");
			builder.put(grammarAccess.getWhileAccess().getGroup(), "rule__While__Group__0");
			builder.put(grammarAccess.getParameterCallAccess().getGroup(), "rule__ParameterCall__Group__0");
			builder.put(grammarAccess.getEqualExpressionAccess().getGroup(), "rule__EqualExpression__Group__0");
			builder.put(grammarAccess.getEqualExpressionAccess().getGroup_1(), "rule__EqualExpression__Group_1__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup(), "rule__ComparisonExpression__Group__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup_1(), "rule__ComparisonExpression__Group_1__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup_1_0_0(), "rule__ComparisonExpression__Group_1_0_0__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup_1_0_1(), "rule__ComparisonExpression__Group_1_0_1__0");
			builder.put(grammarAccess.getAddExpressionAccess().getGroup(), "rule__AddExpression__Group__0");
			builder.put(grammarAccess.getAddExpressionAccess().getGroup_1(), "rule__AddExpression__Group_1__0");
			builder.put(grammarAccess.getAddExpressionAccess().getGroup_1_0_0(), "rule__AddExpression__Group_1_0_0__0");
			builder.put(grammarAccess.getAddExpressionAccess().getGroup_1_0_1(), "rule__AddExpression__Group_1_0_1__0");
			builder.put(grammarAccess.getMultExpressionAccess().getGroup(), "rule__MultExpression__Group__0");
			builder.put(grammarAccess.getMultExpressionAccess().getGroup_1(), "rule__MultExpression__Group_1__0");
			builder.put(grammarAccess.getMultExpressionAccess().getGroup_1_0_0(), "rule__MultExpression__Group_1_0_0__0");
			builder.put(grammarAccess.getMultExpressionAccess().getGroup_1_0_1(), "rule__MultExpression__Group_1_0_1__0");
			builder.put(grammarAccess.getLiteralsExpressionAccess().getGroup_2(), "rule__LiteralsExpression__Group_2__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getLogoProgramAccess().getInstructionsAssignment_1(), "rule__LogoProgram__InstructionsAssignment_1");
			builder.put(grammarAccess.getLogoProgramAccess().getInstructionsAssignment_2(), "rule__LogoProgram__InstructionsAssignment_2");
			builder.put(grammarAccess.getBackwardAccess().getStepsAssignment_1(), "rule__Backward__StepsAssignment_1");
			builder.put(grammarAccess.getForwardAccess().getStepsAssignment_1(), "rule__Forward__StepsAssignment_1");
			builder.put(grammarAccess.getLeftAccess().getAngleAssignment_2(), "rule__Left__AngleAssignment_2");
			builder.put(grammarAccess.getRightAccess().getAngleAssignment_2(), "rule__Right__AngleAssignment_2");
			builder.put(grammarAccess.getConstantAccess().getIntegerValueAssignment_1(), "rule__Constant__IntegerValueAssignment_1");
			builder.put(grammarAccess.getProcCallAccess().getDeclarationAssignment_0(), "rule__ProcCall__DeclarationAssignment_0");
			builder.put(grammarAccess.getProcCallAccess().getActualArgsAssignment_2(), "rule__ProcCall__ActualArgsAssignment_2");
			builder.put(grammarAccess.getProcCallAccess().getActualArgsAssignment_3_1(), "rule__ProcCall__ActualArgsAssignment_3_1");
			builder.put(grammarAccess.getProcDeclarationAccess().getNameAssignment_2(), "rule__ProcDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getProcDeclarationAccess().getArgsAssignment_3(), "rule__ProcDeclaration__ArgsAssignment_3");
			builder.put(grammarAccess.getProcDeclarationAccess().getInstructionsAssignment_4(), "rule__ProcDeclaration__InstructionsAssignment_4");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getBlockAccess().getInstructionsAssignment_2(), "rule__Block__InstructionsAssignment_2");
			builder.put(grammarAccess.getIfAccess().getConditionAssignment_0_1(), "rule__If__ConditionAssignment_0_1");
			builder.put(grammarAccess.getIfAccess().getThenPartAssignment_0_2(), "rule__If__ThenPartAssignment_0_2");
			builder.put(grammarAccess.getIfAccess().getElsePartAssignment_0_3(), "rule__If__ElsePartAssignment_0_3");
			builder.put(grammarAccess.getIfAccess().getConditionAssignment_1_1(), "rule__If__ConditionAssignment_1_1");
			builder.put(grammarAccess.getIfAccess().getThenPartAssignment_1_2(), "rule__If__ThenPartAssignment_1_2");
			builder.put(grammarAccess.getRepeatAccess().getConditionAssignment_1(), "rule__Repeat__ConditionAssignment_1");
			builder.put(grammarAccess.getRepeatAccess().getBlockAssignment_2(), "rule__Repeat__BlockAssignment_2");
			builder.put(grammarAccess.getWhileAccess().getConditionAssignment_1(), "rule__While__ConditionAssignment_1");
			builder.put(grammarAccess.getWhileAccess().getBlockAssignment_2(), "rule__While__BlockAssignment_2");
			builder.put(grammarAccess.getParameterCallAccess().getParameterAssignment_1(), "rule__ParameterCall__ParameterAssignment_1");
			builder.put(grammarAccess.getEqualExpressionAccess().getRhsAssignment_1_2(), "rule__EqualExpression__RhsAssignment_1_2");
			builder.put(grammarAccess.getComparisonExpressionAccess().getRhsAssignment_1_1(), "rule__ComparisonExpression__RhsAssignment_1_1");
			builder.put(grammarAccess.getAddExpressionAccess().getRhsAssignment_1_1(), "rule__AddExpression__RhsAssignment_1_1");
			builder.put(grammarAccess.getMultExpressionAccess().getRhsAssignment_1_1(), "rule__MultExpression__RhsAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LogoGrammarAccess grammarAccess;

	@Override
	protected InternalLogoParser createParser() {
		InternalLogoParser result = new InternalLogoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LogoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LogoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
