/*
 * generated by Xtext
 */
package example.logo.xtext_editor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogoTextualSyntaxRuntimeModule extends example.logo.xtext_editor.AbstractLogoTextualSyntaxRuntimeModule {

}
