/*
 * generated by Xtext
 */
package example.logo.xtext_editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;


/**
 * Use this class to register components to be used within the IDE.
 */
public class LogoTextualSyntaxUiModule extends example.logo.xtext_editor.ui.AbstractLogoTextualSyntaxUiModule {
	public LogoTextualSyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
