/*
* generated by Xtext
*/
package fr.inria.diverse.k3.example.logo.xtext_editor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LogoTextualSyntaxAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/diverse/k3/example/logo/xtext_editor/parser/antlr/internal/InternalLogoTextualSyntax.tokens");
	}
}
