/*
 * generated by Xtext
 */
package example.logo.xtext_editor.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import example.logo.model.logoASM.Back;
import example.logo.model.logoASM.Block;
import example.logo.model.logoASM.Clear;
import example.logo.model.logoASM.Constant;
import example.logo.model.logoASM.Div;
import example.logo.model.logoASM.Equals;
import example.logo.model.logoASM.Forward;
import example.logo.model.logoASM.Greater;
import example.logo.model.logoASM.If;
import example.logo.model.logoASM.Left;
import example.logo.model.logoASM.LogoASMPackage;
import example.logo.model.logoASM.LogoProgram;
import example.logo.model.logoASM.Lower;
import example.logo.model.logoASM.Minus;
import example.logo.model.logoASM.Mult;
import example.logo.model.logoASM.Parameter;
import example.logo.model.logoASM.ParameterCall;
import example.logo.model.logoASM.PenDown;
import example.logo.model.logoASM.PenUp;
import example.logo.model.logoASM.Plus;
import example.logo.model.logoASM.ProcCall;
import example.logo.model.logoASM.ProcDeclaration;
import example.logo.model.logoASM.Repeat;
import example.logo.model.logoASM.Right;
import example.logo.model.logoASM.While;
import example.logo.xtext_editor.services.LogoTextualSyntaxGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public abstract class AbstractLogoTextualSyntaxSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LogoTextualSyntaxGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == LogoASMPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case LogoASMPackage.BACK:
				sequence_Back(context, (Back) semanticObject); 
				return; 
			case LogoASMPackage.BLOCK:
				sequence_Block(context, (Block) semanticObject); 
				return; 
			case LogoASMPackage.CLEAR:
				sequence_Clear(context, (Clear) semanticObject); 
				return; 
			case LogoASMPackage.CONSTANT:
				sequence_Constant(context, (Constant) semanticObject); 
				return; 
			case LogoASMPackage.DIV:
				sequence_MultExpression(context, (Div) semanticObject); 
				return; 
			case LogoASMPackage.EQUALS:
				sequence_EqualExpression(context, (Equals) semanticObject); 
				return; 
			case LogoASMPackage.FORWARD:
				sequence_Forward(context, (Forward) semanticObject); 
				return; 
			case LogoASMPackage.GREATER:
				sequence_ComparisonExpression(context, (Greater) semanticObject); 
				return; 
			case LogoASMPackage.IF:
				sequence_If(context, (If) semanticObject); 
				return; 
			case LogoASMPackage.LEFT:
				sequence_Left(context, (Left) semanticObject); 
				return; 
			case LogoASMPackage.LOGO_PROGRAM:
				sequence_LogoProgram(context, (LogoProgram) semanticObject); 
				return; 
			case LogoASMPackage.LOWER:
				sequence_ComparisonExpression(context, (Lower) semanticObject); 
				return; 
			case LogoASMPackage.MINUS:
				sequence_AddExpression(context, (Minus) semanticObject); 
				return; 
			case LogoASMPackage.MULT:
				sequence_MultExpression(context, (Mult) semanticObject); 
				return; 
			case LogoASMPackage.PARAMETER:
				sequence_Parameter(context, (Parameter) semanticObject); 
				return; 
			case LogoASMPackage.PARAMETER_CALL:
				sequence_ParameterCall(context, (ParameterCall) semanticObject); 
				return; 
			case LogoASMPackage.PEN_DOWN:
				sequence_PenDown(context, (PenDown) semanticObject); 
				return; 
			case LogoASMPackage.PEN_UP:
				sequence_PenUp(context, (PenUp) semanticObject); 
				return; 
			case LogoASMPackage.PLUS:
				sequence_AddExpression(context, (Plus) semanticObject); 
				return; 
			case LogoASMPackage.PROC_CALL:
				sequence_ProcCall(context, (ProcCall) semanticObject); 
				return; 
			case LogoASMPackage.PROC_DECLARATION:
				sequence_ProcDeclaration(context, (ProcDeclaration) semanticObject); 
				return; 
			case LogoASMPackage.REPEAT:
				sequence_Repeat(context, (Repeat) semanticObject); 
				return; 
			case LogoASMPackage.RIGHT:
				sequence_Right(context, (Right) semanticObject); 
				return; 
			case LogoASMPackage.WHILE:
				sequence_While(context, (While) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (lhs=AddExpression_Minus_1_0_1_0 rhs=MultExpression)
	 */
	protected void sequence_AddExpression(EObject context, Minus semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getAddExpressionAccess().getMinusLhsAction_1_0_1_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getAddExpressionAccess().getRhsMultExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=AddExpression_Plus_1_0_0_0 rhs=MultExpression)
	 */
	protected void sequence_AddExpression(EObject context, Plus semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getAddExpressionAccess().getPlusLhsAction_1_0_0_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getAddExpressionAccess().getRhsMultExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     steps=LiteralsExpression
	 */
	protected void sequence_Back(EObject context, Back semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BACK__STEPS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BACK__STEPS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getBackAccess().getStepsLiteralsExpressionParserRuleCall_1_0(), semanticObject.getSteps());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (instructions+=BInstruction*)
	 */
	protected void sequence_Block(EObject context, Block semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     {Clear}
	 */
	protected void sequence_Clear(EObject context, Clear semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=ComparisonExpression_Greater_1_0_0_0 rhs=AddExpression)
	 */
	protected void sequence_ComparisonExpression(EObject context, Greater semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getComparisonExpressionAccess().getGreaterLhsAction_1_0_0_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getComparisonExpressionAccess().getRhsAddExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=ComparisonExpression_Lower_1_0_1_0 rhs=AddExpression)
	 */
	protected void sequence_ComparisonExpression(EObject context, Lower semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getComparisonExpressionAccess().getLowerLhsAction_1_0_1_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getComparisonExpressionAccess().getRhsAddExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     integerValue=EInt
	 */
	protected void sequence_Constant(EObject context, Constant semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.CONSTANT__INTEGER_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.CONSTANT__INTEGER_VALUE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getConstantAccess().getIntegerValueEIntParserRuleCall_1_0(), semanticObject.getIntegerValue());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=EqualExpression_Equals_1_0 rhs=ComparisonExpression)
	 */
	protected void sequence_EqualExpression(EObject context, Equals semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getEqualExpressionAccess().getEqualsLhsAction_1_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getEqualExpressionAccess().getRhsComparisonExpressionParserRuleCall_1_2_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     steps=LiteralsExpression
	 */
	protected void sequence_Forward(EObject context, Forward semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.FORWARD__STEPS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.FORWARD__STEPS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getForwardAccess().getStepsLiteralsExpressionParserRuleCall_1_0(), semanticObject.getSteps());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     ((condition=LiteralsExpression thenPart=Block elsePart=Block) | (condition=LiteralsExpression thenPart=Block))
	 */
	protected void sequence_If(EObject context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     angle=LiteralsExpression
	 */
	protected void sequence_Left(EObject context, Left semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.LEFT__ANGLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.LEFT__ANGLE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getLeftAccess().getAngleLiteralsExpressionParserRuleCall_2_0(), semanticObject.getAngle());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (instructions+=Instruction instructions+=Instruction*)
	 */
	protected void sequence_LogoProgram(EObject context, LogoProgram semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=MultExpression_Div_1_0_1_0 rhs=LiteralsExpression)
	 */
	protected void sequence_MultExpression(EObject context, Div semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getMultExpressionAccess().getDivLhsAction_1_0_1_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getMultExpressionAccess().getRhsLiteralsExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (lhs=MultExpression_Mult_1_0_0_0 rhs=LiteralsExpression)
	 */
	protected void sequence_MultExpression(EObject context, Mult semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__LHS));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.BINARY_EXP__RHS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getMultExpressionAccess().getMultLhsAction_1_0_0_0(), semanticObject.getLhs());
		feeder.accept(grammarAccess.getMultExpressionAccess().getRhsLiteralsExpressionParserRuleCall_1_1_0(), semanticObject.getRhs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     parameter=[Parameter|EString]
	 */
	protected void sequence_ParameterCall(EObject context, ParameterCall semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.PARAMETER_CALL__PARAMETER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.PARAMETER_CALL__PARAMETER));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getParameterCallAccess().getParameterParameterEStringParserRuleCall_1_0_1(), semanticObject.getParameter());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     name=EString
	 */
	protected void sequence_Parameter(EObject context, Parameter semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.PARAMETER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.PARAMETER__NAME));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getParameterAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     {PenDown}
	 */
	protected void sequence_PenDown(EObject context, PenDown semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     {PenUp}
	 */
	protected void sequence_PenUp(EObject context, PenUp semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (declaration=[ProcDeclaration|EString] actualArgs+=LiteralsExpression? actualArgs+=LiteralsExpression*)
	 */
	protected void sequence_ProcCall(EObject context, ProcCall semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EString args+=Parameter* instructions+=Instruction instructions+=Instruction*)
	 */
	protected void sequence_ProcDeclaration(EObject context, ProcDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (condition=LiteralsExpression block=Block)
	 */
	protected void sequence_Repeat(EObject context, Repeat semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.CONTROL_STRUCTURE__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.CONTROL_STRUCTURE__CONDITION));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.REPEAT__BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.REPEAT__BLOCK));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRepeatAccess().getConditionLiteralsExpressionParserRuleCall_1_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getRepeatAccess().getBlockBlockParserRuleCall_2_0(), semanticObject.getBlock());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     angle=LiteralsExpression
	 */
	protected void sequence_Right(EObject context, Right semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.RIGHT__ANGLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.RIGHT__ANGLE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRightAccess().getAngleLiteralsExpressionParserRuleCall_2_0(), semanticObject.getAngle());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (condition=LiteralsExpression block=Block)
	 */
	protected void sequence_While(EObject context, While semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.CONTROL_STRUCTURE__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.CONTROL_STRUCTURE__CONDITION));
			if(transientValues.isValueTransient(semanticObject, LogoASMPackage.Literals.WHILE__BLOCK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LogoASMPackage.Literals.WHILE__BLOCK));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getWhileAccess().getConditionLiteralsExpressionParserRuleCall_1_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getWhileAccess().getBlockBlockParserRuleCall_2_0(), semanticObject.getBlock());
		feeder.finish();
	}
}
