/*
* generated by Xtext
*/
package fr.inria.diverse.k3.example.logo.xtext_editor;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LogoTextualSyntaxStandaloneSetup extends LogoTextualSyntaxStandaloneSetupGenerated{

	public static void doSetup() {
		new LogoTextualSyntaxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

