/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogoTextualSyntaxRuntimeModule extends fr.inria.diverse.k3.example.logo.xtext_editor.AbstractLogoTextualSyntaxRuntimeModule {

}
