/*
* generated by Xtext
*/
package fr.inria.diverse.k3.example.logo.xtext_editor.ui.outline

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class LogoTextualSyntaxOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
	
}
