/*
 * generated by Xtext
 */
package example.logo.xtext_editor.ui.contentassist

import example.logo.xtext_editor.ui.contentassist.AbstractLogoTextualSyntaxProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LogoTextualSyntaxProposalProvider extends AbstractLogoTextualSyntaxProposalProvider {
}
