/*
 * generated by Xtext 2.14.0
 */
package fr.inria.sed.logo.xtext.ui.tests;

import com.google.inject.Injector;
import fr.inria.sed.logo.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LogoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.inria.sed.logo.xtext.Logo");
	}

}
