/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.k3.example.logo.xtext_editor.ui.internal.LogoTextualSyntaxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogoTextualSyntaxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LogoTextualSyntaxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LogoTextualSyntaxActivator.getInstance().getInjector(LogoTextualSyntaxActivator.FR_INRIA_DIVERSE_K3_EXAMPLE_LOGO_XTEXT_EDITOR_LOGOTEXTUALSYNTAX);
	}
	
}
