/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LogoTextualSyntaxUiModule extends fr.inria.diverse.k3.example.logo.xtext_editor.ui.AbstractLogoTextualSyntaxUiModule {
	public LogoTextualSyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
