/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class LogoTextualSyntaxScopeProvider extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider {

}
