/*
 * generated by Xtext
 */
package fr.inria.diverse.k3.example.logo.xtext_editor.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLogoTextualSyntaxValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.kermeta.org/logoASM"));
		return result;
	}
}
